channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=1.0
- nodejs=11
- nbconvert=5.5
- widgetsnbextension=3.5
- vtk
- mayavi
# Python Kernel
- ipykernel=5.1
- ipyevents
- ipywidgets=7.5
- matplotlib=3.1
- pandas=0.24
- python=3.7
# C++ Kernel
- xeus-cling=0.6
- xtensor=0.20.8
- xtensor-blas=0.16.1
- xwidgets=0.18.0
- xleaflet=0.9.0
- pip:
  - PyQt5